### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by itskingori** [tsu-shiuan/snapshooter#2]
Possibly mention how to use it, the flags available, the docker image. Basically something [like this][1].

[1]: https://github.com/skymill/automated-ebs-snapshots/blob/1b536167e91ac89297f84b5ad128ec279247bf85/README.rst

**Comment by itskingori** [comment]
And also add a CHANGELOG since you're cutting releases. If someone is using your tool and you bump they would like to know what we're bumping.

Since there isn't one already, you can fill it in with details of the previously released version while you're at it.

**Comment by tsu-shiuan** [comment]
Stale
