### ISSUE TITLE
Question: clarify on snapshot listing logic

### ISSUE THREAD

**Issue by itskingori** [tsu-shiuan/snapshooter#3]
There's nothing wrong with these lines ... just unclear about what they do and hoping you could explain a little bit more. See:

https://github.com/tsu-shiuan/snapshooter/blob/32c779edd246dc97fe8d723cc3518f3907d078b2/snapshooter.py#L38-L42

**Comment by tsu-shiuan** [comment]
@itskingori 
http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Client.describe_snapshots

We're retrieving the snapshot info using a filter. And thereafter sorting it by StartTime. Sorting it makes the the print statements later on more user friendly.

**Comment by itskingori** [comment]
👍
